### ISSUE TITLE
Switch from tslint because it's long since deprecated

### ISSUE THREAD

**Issue by bradzacher** [johnsoncodehk/tsslint#4]
https://github.com/palantir/tslint/issues/4534

TSLint is deprecated in favour of @typescript-eslint and has been for almost 5 years now.

It is no longer maintained and most codebases have entirely migrated off of it and onto @typescript-eslint - which you can see from the usage numbers - tslint is dropping and @typescript-eslint is rising (currently 1.9m/wk vs 24m/wk, respectively).

If you need help with any aspects of building for ESLint or typescript-eslint, please don't hesitate to chat with us on discord - https://discord.gg/FSxKq8Tdyg

**Comment by johnsoncodehk** [comment]
This project has no dependency on TSLint. It is compatible with TSLint rules simply because it is easy to do so. However, I also found that doing this may not have much significance, as TSLint rules can be easily rewritten in TSSLint. To avoid confusion, I think it is possible to remove TSLint compatibility. (It is just a function)
